# Generated by Django 5.1.1 on 2024-10-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('STAFF', 'Staff'), ('WAREHOUSE_MANAGER', 'Warehouse Manager'), ('WAREHOUSE_STAFF', 'Warehouse Staff'), ('STORE_MANAGER', 'Store Manager'), ('STORE_STAFF', 'Store Staff')], max_length=30),
        ),
    ]
