# Generated by Django 5.1.1 on 2024-10-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('RECEIVED', 'received'), ('CANCELLED', 'cancelled')], default='PENDING', max_length=100),
        ),
    ]
