# Generated by Django 5.1.1 on 2024-10-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_order_order_date_alter_orderitem_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransfer',
            name='date_transferred',
            field=models.DateField(auto_now_add=True),
        ),
    ]
