# Generated by Django 5.1.1 on 2024-10-18 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_order_created_by_alter_orderitem_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='store',
        ),
    ]
