# Generated by Django 5.1.1 on 2024-10-05 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storestock',
            unique_together={('stock_code', 'store', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='warehousestock',
            unique_together={('stock_code', 'warehouse', 'supplier')},
        ),
        migrations.RemoveField(
            model_name='storestock',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storestock',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='warehousestock',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='warehousestock',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='storestock',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_stocks', to='storages.store'),
        ),
        migrations.AddField(
            model_name='storestock',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_stocks', to='storages.supplier'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_stocks', to='storages.supplier'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_stocks', to='storages.warehouse'),
        ),
    ]
