# Generated by Django 5.1.1 on 2024-10-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_storestock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_active_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
