# Generated by Django 5.1.1 on 2024-10-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_storestock_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestock',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
