# Generated by Django 5.1.1 on 2024-10-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storestock',
            name='low_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='low_stock',
            field=models.BooleanField(default=False),
        ),
    ]
