# Generated by Django 5.1.1 on 2024-10-17 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_low_stock_storestock_low_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storestock',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store_stocks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehousestock',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_stocks_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
