# Generated by Django 5.1.1 on 2024-10-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_reorder_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestock',
            name='price',
            field=models.PositiveIntegerField(default=0.0),
            preserve_default=False,
        ),
    ]
